name: Deploy to ASG via ALB

# Trigger deployment on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to ASG via ALB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 400 key.pem

      - name: Get ASG Instance IPs
        id: get-instances
        run: |
          INSTANCE_IDS=$(aws autoscaling describe-auto-scaling-groups \
            --auto-scaling-group-name my-asg \
            --query "AutoScalingGroups[0].Instances[*].InstanceId" --output text)
          
          INSTANCE_IPS=$(aws ec2 describe-instances \
            --instance-ids $INSTANCE_IDS \
            --query "Reservations[*].Instances[*].PublicDnsName" --output text)
          
          echo "INSTANCE_IPS=$INSTANCE_IPS" >> $GITHUB_ENV

      - name: Deploy to ASG Instances
        run: |
          for instance in $INSTANCE_IPS; do
            echo "Deploying to $instance..."
            ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.USERNAME }}@$instance << EOF
              sudo apt-get update -y
              sudo apt-get install -y apache2
              sudo systemctl restart apache2
              cd /var/www/html
              git pull origin main
            EOF
          done

      - name: Verify Deployment via ALB
        run: curl -I http://${{ secrets.DOMAIN_NAME }}
