name: Deploy to ASG Behind ALB

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to ASG & ALB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

            - name: Get ASG Instances Public IPs
        id: get-instances
        run: |
          ASG_NAME="git-ASG"  # Your ASG Name

          # Fetch ASG instance IDs
          INSTANCE_IDS=$(aws autoscaling describe-auto-scaling-groups \
            --auto-scaling-group-name $ASG_NAME \
            --query "AutoScalingGroups[0].Instances[*].InstanceId" \
            --region us-east-1 \
            --output text)

          if [ -z "$INSTANCE_IDS" ]; then
            echo "❌ No instances found in ASG: $ASG_NAME"
            exit 1
          fi

          echo "✅ Found Instances: $INSTANCE_IDS"

          # Fetch instance public DNS names (comma-separated)
          INSTANCE_IPS=$(aws ec2 describe-instances \
            --instance-ids $INSTANCE_IDS \
            --query "Reservations[*].Instances[*].PublicDnsName" \
            --region us-east-1 \
            --output text | tr '\n' ',' | sed 's/,$//')

          if [ -z "$INSTANCE_IPS" ]; then
            echo "❌ No public DNS found for instances: $INSTANCE_IDS"
            exit 1
          fi

          echo "INSTANCE_IPS=$INSTANCE_IPS" >> $GITHUB_ENV
          echo "✅ Found Public DNS: $INSTANCE_IPS"

      - name: Deploy to ASG Instances via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.INSTANCE_IPS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt-get -y update
            sudo apt-get install -y apache2
            sudo systemctl start apache2
            sudo systemctl enable apache2
            cd home
            sudo mv * /var/www/html

      - name: Verify Deployment via ALB
        run: |
          ALB_NAME="git-ALB"  # Your ALB Name

          ALB_DNS=$(aws elbv2 describe-load-balancers \
            --names $ALB_NAME \
            --query "LoadBalancers[0].DNSName" \
            --region us-east-1 \
            --output text)

          if [ -z "$ALB_DNS" ]; then
            echo "❌ No ALB found with name: $ALB_NAME"
            exit 1
          fi

          echo "✅ ALB DNS: http://$ALB_DNS"
          curl -I http://$ALB_DNS

      - name: Verify Route 53 Custom Domain
        run: |
          echo "✅ Verifying custom domain: http://${{ secrets.DOMAIN_NAME }}"
          curl -I http://${{ secrets.DOMAIN_NAME }}
